let money = 10500;
console.log(money);
let income = 'Фриланс 2500 грн';
console.log(income);
let addExpenses = `Интернет 230 грн, такси  600 грн,
    Коммуналка  1200 грн`;
addExpenses.length;
let denosit = true;
let mission = 50000;
let period = 4;
let budgetDay = money / 30;
console.log(budgetDay);
typeof (money);
typeof (income);
typeof (deposit);
console.log(income);
console.log(denosit);
console.log(mission + ' ' + 'гривен');
console.log(addExpenses);
console.log(period + ' ' + 'месяцев');
addExpenses.toLowerCase();
addExpenses.split();